import { Component, ElementRef, computed, inject, signal, viewChild } from '@angular/core';
import { Search } from './search/search';
import { PollinationsAuthService } from './services/pollinations-auth.service';

// Pollinations image generation endpoint.
// Opcional: clave de respaldo para usuarios en modo anónimo (pk_ o sk_).
// Nunca expongas una clave `sk_` en código de cliente.
const POLLINATIONS_FALLBACK_API_KEY = '';
const POLLINATIONS_IMAGE_BASE = 'https://gen.pollinations.ai/image';
const POLLINATIONS_MODEL = 'flux';

type FusionResult = {
  pokemons: string[];
  prompt: string;
  imageUrl: string;
};

type ImageStatus = 'idle' | 'loading' | 'loaded' | 'error';

const QUALITIES = [
  'hideous',
  'atrocious',
  'happy',
  'cute',
  'sickly',
  'derpy',
  'powerful',
  'muscular',
] as const;

type Quality = (typeof QUALITIES)[number];

const QUALITY_DESCRIPTORS: Record<Quality, string> = {
  hideous: 'hideous and grotesque',
  atrocious: 'monstrous and terrifying',
  happy: 'happy and cheerful',
  cute: 'cute and adorable',
  sickly: 'sickly and unsettling',
  derpy: 'derpy and silly-looking',
  powerful: 'powerful and imposing',
  muscular: 'muscular and buff',
};

function pickRandomQuality(): Quality {
  return QUALITIES[Math.floor(Math.random() * QUALITIES.length)]!;
}

const pokelist = [
  'bulbasaur',
  'ivysaur',
  'venusaur',
  'charmander',
  'charmeleon',
  'charizard',
  'squirtle',
  'wartortle',
  'blastoise',
  'caterpie',
  'metapod',
  'butterfree',
  'weedle',
  'kakuna',
  'beedrill',
  'pidgey',
  'pidgeotto',
  'pidgeot',
  'rattata',
  'raticate',
  'spearow',
  'fearow',
  'ekans',
  'arbok',
  'pikachu',
  'raichu',
  'sandshrew',
  'sandslash',
  'nidoran♀',
  'nidorina',
  'nidoqueen',
  'nidoran♂',
  'nidorino',
  'nidoking',
  'clefairy',
  'clefable',
  'vulpix',
  'ninetales',
  'jigglypuff',
  'wigglytuff',
  'zubat',
  'golbat',
  'oddish',
  'gloom',
  'vileplume',
  'paras',
  'parasect',
  'venonat',
  'venomoth',
  'diglett',
  'dugtrio',
  'meowth',
  'persian',
  'psyduck',
  'golduck',
  'mankey',
  'primeape',
  'growlithe',
  'arcanine',
  'poliwag',
  'poliwhirl',
  'poliwrath',
  'abra',
  'kadabra',
  'alakazam',
  'machop',
  'machoke',
  'machamp',
  'bellsprout',
  'weepinbell',
  'victreebel',
  'tentacool',
  'tentacruel',
  'geodude',
  'graveler',
  'golem',
  'ponyta',
  'rapidash',
  'slowpoke',
  'slowbro',
  'magnemite',
  'magneton',
  'farfetch’d',
  'doduo',
  'dodrio',
  'seel',
  'dewgong',
  'grimer',
  'muk',
  'shellder',
  'cloyster',
  'gastly',
  'haunter',
  'gengar',
  'onix',
  'drowzee',
  'hypno',
  'krabby',
  'kingler',
  'voltorb',
  'electrode',
  'exeggcute',
  'exeggutor',
  'cubone',
  'marowak',
  'hitmonlee',
  'hitmonchan',
  'lickitung',
  'koffing',
  'weezing',
  'rhyhorn',
  'rhydon',
  'chansey',
  'tangela',
  'kangaskhan',
  'horsea',
  'seadra',
  'goldeen',
  'seaking',
  'staryu',
  'starmie',
  'mr. mime',
  'scyther',
  'jynx',
  'electabuzz',
  'magmar',
  'pinsir',
  'tauros',
  'magikarp',
  'gyarados',
  'lapras',
  'ditto',
  'eevee',
  'vaporeon',
  'jolteon',
  'flareon',
  'porygon',
  'omanyte',
  'omastar',
  'kabuto',
  'kabutops',
  'aerodactyl',
  'snorlax',
  'articuno',
  'zapdos',
  'moltres',
  'dratini',
  'dragonair',
  'dragonite',
  'mewtwo',
  'mew',
  'chikorita',
  'bayleef',
  'meganium',
  'cyndaquil',
  'quilava',
  'typhlosion',
  'totodile',
  'croconaw',
  'feraligatr',
  'sentret',
  'furret',
  'hoothoot',
  'noctowl',
  'ledyba',
  'ledian',
  'spinarak',
  'ariados',
  'crobat',
  'chinchou',
  'lanturn',
  'pichu',
  'cleffa',
  'igglybuff',
  'togepi',
  'togetic',
  'natu',
  'xatu',
  'mareep',
  'flaaffy',
  'ampharos',
  'bellossom',
  'marill',
  'azumarill',
  'sudowoodo',
  'politoed',
  'hoppip',
  'skiploom',
  'jumpluff',
  'aipom',
  'sunkern',
  'sunflora',
  'yanma',
  'wooper',
  'quagsire',
  'espeon',
  'umbreon',
  'murkrow',
  'slowking',
  'misdreavus',
  'unown',
  'wobbuffet',
  'girafarig',
  'pineco',
  'forretress',
  'dunsparce',
  'gligar',
  'steelix',
  'snubbull',
  'granbull',
  'qwilfish',
  'scizor',
  'shuckle',
  'heracross',
  'sneasel',
  'teddiursa',
  'ursaring',
  'slugma',
  'magcargo',
  'swinub',
  'piloswine',
  'corsola',
  'remoraid',
  'octillery',
  'delibird',
  'mantine',
  'skarmory',
  'houndour',
  'houndoom',
  'kingdra',
  'phanpy',
  'donphan',
  'porygon2',
  'stantler',
  'smeargle',
  'tyrogue',
  'hitmontop',
  'smoochum',
  'elekid',
  'magby',
  'miltank',
  'blissey',
  'raikou',
  'entei',
  'suicune',
  'larvitar',
  'pupitar',
  'tyranitar',
  'lugia',
  'ho-oh',
  'celebi',
  'treecko',
  'grovyle',
  'sceptile',
  'torchic',
  'combusken',
  'blaziken',
  'mudkip',
  'marshtomp',
  'swampert',
  'poochyena',
  'mightyena',
  'zigzagoon',
  'linoone',
  'wurmple',
  'silcoon',
  'beautifly',
  'cascoon',
  'dustox',
  'lotad',
  'lombre',
  'ludicolo',
  'seedot',
  'nuzleaf',
  'shiftry',
  'taillow',
  'swellow',
  'wingull',
  'pelipper',
  'ralts',
  'kirlia',
  'gardevoir',
  'surskit',
  'masquerain',
  'shroomish',
  'breloom',
  'slakoth',
  'vigoroth',
  'slaking',
  'nincada',
  'ninjask',
  'shedinja',
  'whismur',
  'loudred',
  'exploud',
  'makuhita',
  'hariyama',
  'azurill',
  'nosepass',
  'skitty',
  'delcatty',
  'sableye',
  'mawile',
  'aron',
  'lairon',
  'aggron',
  'meditite',
  'medicham',
  'electrike',
  'manectric',
  'plusle',
  'minun',
  'volbeat',
  'illumise',
  'roselia',
  'gulpin',
  'swalot',
  'carvanha',
  'sharpedo',
  'wailmer',
  'wailord',
  'numel',
  'camerupt',
  'torkoal',
  'spoink',
  'grumpig',
  'spinda',
  'trapinch',
  'vibrava',
  'flygon',
  'cacnea',
  'cacturne',
  'swablu',
  'altaria',
  'zangoose',
  'seviper',
  'lunatone',
  'solrock',
  'barboach',
  'whiscash',
  'corphish',
  'crawdaunt',
  'baltoy',
  'claydol',
  'lileep',
  'cradily',
  'anorith',
  'armaldo',
  'feebas',
  'milotic',
  'castform',
  'kecleon',
  'shuppet',
  'banette',
  'duskull',
  'dusclops',
  'tropius',
  'chimecho',
  'absol',
  'wynaut',
  'snorunt',
  'glalie',
  'spheal',
  'sealeo',
  'walrein',
  'clamperl',
  'huntail',
  'gorebyss',
  'relicanth',
  'luvdisc',
  'bagon',
  'shelgon',
  'salamence',
  'beldum',
  'metang',
  'metagross',
  'regirock',
  'regice',
  'registeel',
  'latias',
  'latios',
  'kyogre',
  'groudon',
  'rayquaza',
  'jirachi',
  'deoxys',
  'turtwig',
  'grotle',
  'torterra',
  'chimchar',
  'monferno',
  'infernape',
  'piplup',
  'prinplup',
  'empoleon',
  'starly',
  'staravia',
  'staraptor',
  'bidoof',
  'bibarel',
  'kricketot',
  'kricketune',
  'shinx',
  'luxio',
  'luxray',
  'budew',
  'roserade',
  'cranidos',
  'rampardos',
  'shieldon',
  'bastiodon',
  'burmy',
  'wormadam',
  'mothim',
  'combee',
  'vespiquen',
  'pachirisu',
  'buizel',
  'floatzel',
  'cherubi',
  'cherrim',
  'shellos',
  'gastrodon',
  'ambipom',
  'drifloon',
  'drifblim',
  'buneary',
  'lopunny',
  'mismagius',
  'honchkrow',
  'glameow',
  'purugly',
  'chingling',
  'stunky',
  'skuntank',
  'bronzor',
  'bronzong',
  'bonsly',
  'mime jr.',
  'happiny',
  'chatot',
  'spiritomb',
  'gible',
  'gabite',
  'garchomp',
  'munchlax',
  'riolu',
  'lucario',
  'hippopotas',
  'hippowdon',
  'skorupi',
  'drapion',
  'croagunk',
  'toxicroak',
  'carnivine',
  'finneon',
  'lumineon',
  'mantyke',
  'snover',
  'abomasnow',
  'weavile',
  'magnezone',
  'lickilicky',
  'rhyperior',
  'tangrowth',
  'electivire',
  'magmortar',
  'togekiss',
  'yanmega',
  'leafeon',
  'glaceon',
  'gliscor',
  'mamoswine',
  'porygon-z',
  'gallade',
  'probopass',
  'dusknoir',
  'froslass',
  'rotom',
  'uxie',
  'mesprit',
  'azelf',
  'dialga',
  'palkia',
  'heatran',
  'regigigas',
  'giratina',
  'cresselia',
  'phione',
  'manaphy',
  'darkrai',
  'shaymin',
  'arceus',
  'victini',
  'snivy',
  'servine',
  'serperior',
  'tepig',
  'pignite',
  'emboar',
  'oshawott',
  'dewott',
  'samurott',
  'patrat',
  'watchog',
  'lillipup',
  'herdier',
  'stoutland',
  'purrloin',
  'liepard',
  'pansage',
  'simisage',
  'pansear',
  'simisear',
  'panpour',
  'simipour',
  'munna',
  'musharna',
  'pidove',
  'tranquill',
  'unfezant',
  'blitzle',
  'zebstrika',
  'roggenrola',
  'boldore',
  'gigalith',
  'woobat',
  'swoobat',
  'drilbur',
  'excadrill',
  'audino',
  'timburr',
  'gurdurr',
  'conkeldurr',
  'tympole',
  'palpitoad',
  'seismitoad',
  'throh',
  'sawk',
  'sewaddle',
  'swadloon',
  'leavanny',
  'venipede',
  'whirlipede',
  'scolipede',
  'cottonee',
  'whimsicott',
  'petilil',
  'lilligant',
  'basculin',
  'sandile',
  'krokorok',
  'krookodile',
  'darumaka',
  'darmanitan',
  'maractus',
  'dwebble',
  'crustle',
  'scraggy',
  'scrafty',
  'sigilyph',
  'yamask',
  'cofagrigus',
  'tirtouga',
  'carracosta',
  'archen',
  'archeops',
  'trubbish',
  'garbodor',
  'zorua',
  'zoroark',
  'minccino',
  'cinccino',
  'gothita',
  'gothorita',
  'gothitelle',
  'solosis',
  'duosion',
  'reuniclus',
  'ducklett',
  'swanna',
  'vanillite',
  'vanillish',
  'vanilluxe',
  'deerling',
  'sawsbuck',
  'emolga',
  'karrablast',
  'escavalier',
  'foongus',
  'amoonguss',
  'frillish',
  'jellicent',
  'alomomola',
  'joltik',
  'galvantula',
  'ferroseed',
  'ferrothorn',
  'klink',
  'klang',
  'klinklang',
  'tynamo',
  'eelektrik',
  'eelektross',
  'elgyem',
  'beheeyem',
  'litwick',
  'lampent',
  'chandelure',
  'axew',
  'fraxure',
  'haxorus',
  'cubchoo',
  'beartic',
  'cryogonal',
  'shelmet',
  'accelgor',
  'stunfisk',
  'mienfoo',
  'mienshao',
  'druddigon',
  'golett',
  'golurk',
  'pawniard',
  'bisharp',
  'bouffalant',
  'rufflet',
  'braviary',
  'vullaby',
  'mandibuzz',
  'heatmor',
  'durant',
  'deino',
  'zweilous',
  'hydreigon',
  'larvesta',
  'volcarona',
  'cobalion',
  'terrakion',
  'virizion',
  'tornadus',
  'thundurus',
  'reshiram',
  'zekrom',
  'landorus',
  'kyurem',
  'keldeo',
  'meloetta',
  'genesect',
  'chespin',
  'quilladin',
  'chesnaught',
  'fennekin',
  'braixen',
  'delphox',
  'froakie',
  'frogadier',
  'greninja',
  'bunnelby',
  'diggersby',
  'fletchling',
  'fletchinder',
  'talonflame',
  'scatterbug',
  'spewpa',
  'vivillon',
  'litleo',
  'pyroar',
  'flabébé',
  'floette',
  'florges',
  'skiddo',
  'gogoat',
  'pancham',
  'pangoro',
  'furfrou',
  'espurr',
  'meowstic',
  'honedge',
  'doublade',
  'aegislash',
  'spritzee',
  'aromatisse',
  'swirlix',
  'slurpuff',
  'inkay',
  'malamar',
  'binacle',
  'barbaracle',
  'skrelp',
  'dragalge',
  'clauncher',
  'clawitzer',
  'helioptile',
  'heliolisk',
  'tyrunt',
  'tyrantrum',
  'amaura',
  'aurorus',
  'sylveon',
  'hawlucha',
  'dedenne',
  'carbink',
  'goomy',
  'sliggoo',
  'goodra',
  'klefki',
  'phantump',
  'trevenant',
  'pumpkaboo',
  'gourgeist',
  'bergmite',
  'avalugg',
  'noibat',
  'noivern',
  'xerneas',
  'yveltal',
  'zygarde',
  'diancie',
  'hoopa',
  'volcanion',
  'rowlet',
  'dartrix',
  'decidueye',
  'litten',
  'torracat',
  'incineroar',
  'popplio',
  'brionne',
  'primarina',
  'pikipek',
  'trumbeak',
  'toucannon',
  'yungoos',
  'gumshoos',
  'grubbin',
  'charjabug',
  'vikavolt',
  'crabrawler',
  'crabominable',
  'oricorio',
  'cutiefly',
  'ribombee',
  'rockruff',
  'lycanroc',
  'wishiwashi',
  'mareanie',
  'toxapex',
  'mudbray',
  'mudsdale',
  'dewpider',
  'araquanid',
  'fomantis',
  'lurantis',
  'morelull',
  'shiinotic',
  'salandit',
  'salazzle',
  'stufful',
  'bewear',
  'bounsweet',
  'steenee',
  'tsareena',
  'comfey',
  'oranguru',
  'passimian',
  'wimpod',
  'golisopod',
  'sandygast',
  'palossand',
  'pyukumuku',
  'type: null',
  'silvally',
  'minior',
  'komala',
  'turtonator',
  'togedemaru',
  'mimikyu',
  'bruxish',
  'drampa',
  'dhelmise',
  'jangmo-o',
  'hakamo-o',
  'kommo-o',
  'tapu koko',
  'tapu lele',
  'tapu bulu',
  'tapu fini',
  'cosmog',
  'cosmoem',
  'solgaleo',
  'lunala',
  'nihilego',
  'buzzwole',
  'pheromosa',
  'xurkitree',
  'celesteela',
  'kartana',
  'guzzlord',
  'necrozma',
  'magearna',
  'marshadow',
  'poipole',
  'naganadel',
  'stakataka',
  'blacephalon',
  'zeraora',
  'meltan',
  'melmetal',
  'grookey',
  'thwackey',
  'rillaboom',
  'scorbunny',
  'raboot',
  'cinderace',
  'sobble',
  'drizzile',
  'inteleon',
  'skwovet',
  'greedent',
  'rookidee',
  'corvisquire',
  'corviknight',
  'blipbug',
  'dottler',
  'orbeetle',
  'nickit',
  'thievul',
  'gossifleur',
  'eldegoss',
  'wooloo',
  'dubwool',
  'chewtle',
  'drednaw',
  'yamper',
  'boltund',
  'rolycoly',
  'carkol',
  'coalossal',
  'applin',
  'flapple',
  'appletun',
  'silicobra',
  'sandaconda',
  'cramorant',
  'arrokuda',
  'barraskewda',
  'toxel',
  'toxtricity',
  'sizzlipede',
  'centiskorch',
  'clobbopus',
  'grapploct',
  'sinistea',
  'polteageist',
  'hatenna',
  'hattrem',
  'hatterene',
  'impidimp',
  'morgrem',
  'grimmsnarl',
  'obstagoon',
  'perrserker',
  'cursola',
  'sirfetch’d',
  'mr. rime',
  'runerigus',
  'milcery',
  'alcremie',
  'falinks',
  'pincurchin',
  'snom',
  'frosmoth',
  'stonjourner',
  'eiscue',
  'indeedee',
  'morpeko',
  'cufant',
  'copperajah',
  'dracozolt',
  'arctozolt',
  'dracovish',
  'arctovish',
  'duraludon',
  'dreepy',
  'drakloak',
  'dragapult',
  'zacian',
  'zamazenta',
  'eternatus',
  'kubfu',
  'urshifu',
  'zarude',
  'regieleki',
  'regidrago',
  'glastrier',
  'spectrier',
  'calyrex',
  'wyrdeer',
  'kleavor',
  'ursaluna',
  'basculegion',
  'sneasler',
  'overqwil',
  'enamorus',
  'sprigatito',
  'floragato',
  'meowscarada',
  'fuecoco',
  'crocalor',
  'skeledirge',
  'quaxly',
  'quaxwell',
  'quaquaval',
  'lechonk',
  'oinkologne',
  'tarountula',
  'spidops',
  'nymble',
  'lokix',
  'pawmi',
  'pawmo',
  'pawmot',
  'tandemaus',
  'maushold',
  'fidough',
  'dachsbun',
  'smoliv',
  'dolliv',
  'arboliva',
  'squawkabilly',
  'nacli',
  'naclstack',
  'garganacl',
  'charcadet',
  'armarouge',
  'ceruledge',
  'tadbulb',
  'bellibolt',
  'wattrel',
  'kilowattrel',
  'maschiff',
  'mabosstiff',
  'shroodle',
  'grafaiai',
  'bramblin',
  'brambleghast',
  'toedscool',
  'toedscruel',
  'klawf',
  'capsakid',
  'scovillain',
  'rellor',
  'rabsca',
  'flittle',
  'espathra',
  'tinkatink',
  'tinkatuff',
  'tinkaton',
  'wiglett',
  'wugtrio',
  'bombirdier',
  'finizen',
  'palafin',
  'varoom',
  'revavroom',
  'cyclizar',
  'orthworm',
  'glimmet',
  'glimmora',
  'greavard',
  'houndstone',
  'flamigo',
  'cetoddle',
  'cetitan',
  'veluza',
  'dondozo',
  'tatsugiri',
  'annihilape',
  'clodsire',
  'farigiraf',
  'dudunsparce',
  'kingambit',
  'great tusk',
  'scream tail',
  'brute bonnet',
  'flutter mane',
  'slither wing',
  'sandy shocks',
  'iron treads',
  'iron bundle',
  'iron hands',
  'iron jugulis',
  'iron moth',
  'iron thorns',
  'frigibax',
  'arctibax',
  'baxcalibur',
  'gimmighoul',
  'gholdengo',
  'wo-chien',
  'chien-pao',
  'ting-lu',
  'chi-yu',
  'roaring moon',
  'iron valiant',
  'koraidon',
  'miraidon',
  'walking wake',
  'iron leaves',
  'dipplin',
  'poltchageist',
  'sinistcha',
  'okidogi',
  'munkidori',
  'fezandipiti',
  'ogerpon',
  'archaludon',
  'hydrapple',
  'gouging fire',
  'raging bolt',
  'iron boulder',
  'iron crown',
  'terapagos',
  'pecharunt',
];

@Component({
  selector: 'app-root',
  imports: [Search],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {
  private readonly auth = inject(PollinationsAuthService);

  protected readonly title = signal('pokengular');

  protected readonly fusion = signal<FusionResult | null>(null);
  protected readonly imageStatus = signal<ImageStatus>('idle');
  protected readonly isAuthenticated = this.auth.isAuthenticated;
  protected readonly balance = this.auth.balance;
  protected readonly balanceLoading = this.auth.balanceLoading;
  protected readonly notFound = signal<string | null>(null);

  protected readonly errorMessage = computed(() => {
    if (this.imageStatus() !== 'error') {
      return null;
    }
    return this.isAuthenticated()
      ? "Couldn't make the image. Hit Regenerate to try again."
      : "Couldn't make the image. Sign in with Pollinations — the anonymous tier is rate-limited.";
  });

  constructor() {
    // Capture the api_key returned by Pollinations after the OAuth
    // redirect, and clean it from the URL.
    this.auth.handleAuthRedirect();
  }

  buscarFisionPokemonPerfecto(textoCombinado: string): string[] {
    const textoLimpio = textoCombinado.toLowerCase();
    for (let i = 3; i <= textoLimpio.length - 2; i++) {
      const parteIzquierda = textoLimpio.substring(0, i);
      const parteDerecha = textoLimpio.substring(i);
      const pokemonIzquierdo = pokelist.find((p) => p.includes(parteIzquierda));
      const pokemonDerecho = pokelist.find((p) => p.includes(parteDerecha));
      if (pokemonIzquierdo && pokemonDerecho) {
        if (pokemonIzquierdo === pokemonDerecho) {
          return [pokemonIzquierdo];
        }
        return [pokemonIzquierdo, pokemonDerecho];
      }
    }

    return [];
  }

  getFision(txt: string): string[] {
    const arr = this.buscarFisionPokemonPerfecto(txt);

    if (arr[0]) {
      this.notFound.set(null);
      const prompt = this.buildFusionPrompt(arr);
      this.fusion.set({
        pokemons: arr,
        prompt,
        imageUrl: this.buildImageUrl(prompt),
      });
      this.imageStatus.set('loading');
    } else {
      this.notFound.set(txt);
      this.fusion.set(null);
      this.imageStatus.set('idle');
    }

    return arr;
  }

  protected onImageLoad(): void {
    this.imageStatus.set('loaded');
    // Refresh the user's balance so the UI reflects the cost of this
    // generation. Silently no-ops if the user is in anonymous mode.
    void this.auth.refreshBalance();
  }

  protected onImageError(): void {
    this.imageStatus.set('error');
  }

  protected refreshBalance(): void {
    void this.auth.refreshBalance();
  }

  private readonly detailsDialog = viewChild<ElementRef<HTMLDialogElement>>('detailsDialog');

  protected openDetails(): void {
    this.detailsDialog()?.nativeElement.showModal();
  }

  protected closeDetails(): void {
    this.detailsDialog()?.nativeElement.close();
  }

  protected onDialogClick(event: MouseEvent): void {
    // Close when the user clicks the dialog itself (= the backdrop area),
    // but not when they click inside the article content.
    if (event.target === this.detailsDialog()?.nativeElement) {
      this.closeDetails();
    }
  }

  protected regenerate(): void {
    const current = this.fusion();
    if (!current) {
      return;
    }
    this.fusion.set({
      ...current,
      imageUrl: this.buildImageUrl(current.prompt),
    });
    this.imageStatus.set('loading');
  }

  protected signInWithPollinations(): void {
    this.auth.authorize();
  }

  protected signOut(): void {
    this.auth.signOut();
    this.fusion.set(null);
    this.imageStatus.set('idle');
  }

  private buildImageUrl(prompt: string): string {
    const seed = Math.floor(Math.random() * 1_000_000);
    const params = new URLSearchParams({
      model: POLLINATIONS_MODEL,
      width: '512',
      height: '512',
      seed: String(seed),
    });
    const apiKey = this.auth.getApiKey() ?? POLLINATIONS_FALLBACK_API_KEY;
    if (apiKey) {
      params.set('key', apiKey);
    }
    return `${POLLINATIONS_IMAGE_BASE}/${encodeURIComponent(prompt)}?${params.toString()}`;
  }

  private buildFusionPrompt(pokemons: string[]): string {
    const quality = pickRandomQuality();
    const descriptor = QUALITY_DESCRIPTORS[quality];

    const subject =
      pokemons.length === 1
        ? `official pokemon artwork of ${pokemons[0]}`
        : `one pokemon creature hybrid of ${pokemons[0]} and ${pokemons[1]}`;

    return (
      `${subject}, ${descriptor}, draw,` +
      `official pokemon based on videogame style, full body.no artist signature`
    );
  }
}
